package source;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class MaterialCodeGenerator {

	public static final String DETAIL = "$";

//	"LAPIS_ORE" instead of "LAPIS_LAZULI_ORE"
//	"LAPIS_BLOCK" instead of "LAPIS_LAZULI_BLOCK"
//	"JACK_O_LANTERN" instead of ""JACK_O'LANTERN"
	public static void main(String args[]) {
		String[] minecraftMaerial = { "ACACIA_BUTTON", "ACACIA_DOOR", "ACACIA_FENCE", "ACACIA_FENCE_GATE",
				"ACACIA_LEAVES", "ACACIA_LOG", "ACACIA_PLANKS", "ACACIA_PRESSURE_PLATE", "ACACIA_SAPLING",
				"ACACIA_SIGN", "ACACIA_SLAB", "ACACIA_STAIRS", "ACACIA_TRAPDOOR", "ACACIA_WALL_SIGN", "ACACIA_WOOD",
				"ACTIVATOR_RAIL", "AIR", "ALLIUM", "ANCIENT_DEBRIS‌", "ANDESITE", "ANDESITE_SLAB", "ANDESITE_STAIRS",
				"ANDESITE_WALL", "ANVIL", "ATTACHED_MELON_STEM", "ATTACHED_PUMPKIN_STEM", "AZURE_BLUET", "BAMBOO",
				"BAMBOO_SAPLING", "BARREL", "BARRIER", "BEACON", "BEDROCK", "BEETROOTS", "BEEHIVE", "BEE_NEST", "BELL",
				"BIRCH_BUTTON", "BIRCH_DOOR", "BIRCH_FENCE", "BIRCH_FENCE_GATE", "BIRCH_LEAVES", "BIRCH_LOG",
				"BIRCH_PLANKS", "BIRCH_PRESSURE_PLATE", "BIRCH_SAPLING", "BIRCH_SIGN", "BIRCH_SLAB", "BIRCH_STAIRS",
				"BIRCH_TRAPDOOR", "BIRCH_WALL_SIGN", "BIRCH_WOOD", "BLACK_BANNER", "BLACK_BED", "BLACK_CARPET",
				"BLACK_CONCRETE", "BLACK_CONCRETE_POWDER", "BLACK_GLAZED_TERRACOTTA", "BLACK_SHULKER_BOX",
				"BLACK_STAINED_GLASS", "BLACK_STAINED_GLASS_PANE", "BLACK_TERRACOTTA", "BLACK_WALL_BANNER",
				"BLACK_WOOL", "BLAST_FURNACE", "BLOCK_OF_COAL", "BLOCK_OF_DIAMOND", "BLOCK_OF_EMERALD", "BLOCK_OF_GOLD",
				"BLOCK_OF_IRON", "BLOCK_OF_NETHERITE‌", "QUARTZ_BLOCK", "BLOCK_OF_REDSTONE", "BLUE_BANNER", "BLUE_BED",
				"BLUE_CARPET", "BLUE_CONCRETE", "BLUE_CONCRETE_POWDER", "BLUE_GLAZED_TERRACOTTA", "BLUE_ICE",
				"BLUE_ORCHID", "BLUE_SHULKER_BOX", "BLUE_STAINED_GLASS", "BLUE_STAINED_GLASS_PANE", "BLUE_TERRACOTTA",
				"BLUE_WALL_BANNER", "BLUE_WOOL", "BONE_BLOCK", "BOOKSHELF", "BRAIN_CORAL", "BRAIN_CORAL_BLOCK",
				"BRAIN_CORAL_FAN", "BRAIN_CORAL_WALL_FAN", "BREWING_STAND", "BRICK_SLAB", "BRICK_STAIRS", "BRICK_WALL",
				"BRICKS", "BROWN_BANNER", "BROWN_BED", "BROWN_CARPET", "BROWN_CONCRETE", "BROWN_CONCRETE_POWDER",
				"BROWN_GLAZED_TERRACOTTA", "BROWN_MUSHROOM", "BROWN_MUSHROOM_BLOCK", "BROWN_SHULKER_BOX",
				"BROWN_STAINED_GLASS", "BROWN_STAINED_GLASS_PANE", "BROWN_TERRACOTTA", "BROWN_WALL_BANNER",
				"BROWN_WOOL", "BUBBLE_COLUMN", "BUBBLE_CORAL", "BUBBLE_CORAL_BLOCK", "BUBBLE_CORAL_FAN",
				"BUBBLE_CORAL_WALL_FAN", "CACTUS", "CAKE", "CAMPFIRE", "CARROTS", "CARTOGRAPHY_TABLE", "CARVED_PUMPKIN",
				"CAULDRON", "CAVE_AIR", "CHAIN_COMMAND_BLOCK", "CHEST", "CHIPPED_ANVIL", "CHISELED_QUARTZ_BLOCK",
				"CHISELED_RED_SANDSTONE", "CHISELED_SANDSTONE", "CHISELED_STONE_BRICKS", "CHORUS_FLOWER",
				"CHORUS_PLANT", "CLAY", "COAL_ORE", "COARSE_DIRT", "COBBLESTONE", "COBBLESTONE_SLAB",
				"COBBLESTONE_STAIRS", "COBBLESTONE_WALL", "COBWEB", "COCOA", "COMMAND_BLOCK", "COMPOSTER", "CONDUIT",
				"CORNFLOWER", "CRACKED_STONE_BRICKS", "CRAFTING_TABLE", "CREEPER_HEAD", "CREEPER_WALL_HEAD",
				"CUT_RED_SANDSTONE", "CUT_RED_SANDSTONE_SLAB", "CUT_SANDSTONE", "CUT_SANDSTONE_SLAB", "CYAN_BANNER",
				"CYAN_BED", "CYAN_CARPET", "CYAN_CONCRETE", "CYAN_CONCRETE_POWDER", "CYAN_GLAZED_TERRACOTTA",
				"CYAN_SHULKER_BOX", "CYAN_STAINED_GLASS", "CYAN_STAINED_GLASS_PANE", "CYAN_TERRACOTTA",
				"CYAN_WALL_BANNER", "CYAN_WOOL", "DAMAGED_ANVIL", "DANDELION", "DARK_OAK_BUTTON", "DARK_OAK_DOOR",
				"DARK_OAK_FENCE", "DARK_OAK_FENCE_GATE", "DARK_OAK_LEAVES", "DARK_OAK_LOG", "DARK_OAK_PLANKS",
				"DARK_OAK_PRESSURE_PLATE", "DARK_OAK_SAPLING", "DARK_OAK_SIGN", "DARK_OAK_SLAB", "DARK_OAK_STAIRS",
				"DARK_OAK_TRAPDOOR", "DARK_OAK_WALL_SIGN", "DARK_OAK_WOOD", "DARK_PRISMARINE", "DARK_PRISMARINE_SLAB",
				"DARK_PRISMARINE_STAIRS", "DAYLIGHT_DETECTOR", "DEAD_BRAIN_CORAL", "DEAD_BRAIN_CORAL_BLOCK",
				"DEAD_BRAIN_CORAL_FAN", "DEAD_BRAIN_CORAL_WALL_FAN", "DEAD_BUBBLE_CORAL", "DEAD_BUBBLE_CORAL_BLOCK",
				"DEAD_BUBBLE_CORAL_FAN", "DEAD_BUBBLE_CORAL_WALL_FAN", "DEAD_BUSH", "DEAD_FIRE_CORAL",
				"DEAD_FIRE_CORAL_BLOCK", "DEAD_FIRE_CORAL_FAN", "DEAD_FIRE_CORAL_WALL_FAN", "DEAD_HORN_CORAL",
				"DEAD_HORN_CORAL_BLOCK", "DEAD_HORN_CORAL_FAN", "DEAD_HORN_CORAL_WALL_FAN", "DEAD_TUBE_CORAL",
				"DEAD_TUBE_CORAL_BLOCK", "DEAD_TUBE_CORAL_FAN", "DEAD_TUBE_CORAL_WALL_FAN", "DETECTOR_RAIL",
				"DIAMOND_ORE", "DIORITE", "DIORITE_SLAB", "DIORITE_STAIRS", "DIORITE_WALL", "DIRT", "DISPENSER",
				"DRAGON_EGG", "DRAGON_HEAD", "DRAGON_WALL_HEAD", "DRIED_KELP_BLOCK", "DROPPER", "EMERALD_ORE",
				"ENCHANTING_TABLE", "END_GATEWAY", "END_PORTAL", "END_PORTAL_FRAME", "END_ROD", "END_STONE",
				"END_STONE_BRICK_SLAB", "END_STONE_BRICK_STAIRS", "END_STONE_BRICK_WALL", "END_STONE_BRICKS",
				"ENDER_CHEST", "FARMLAND", "FERN", "FIRE", "FIRE_CORAL", "FIRE_CORAL_BLOCK", "FIRE_CORAL_FAN",
				"FIRE_CORAL_WALL_FAN", "FLETCHING_TABLE", "FLOWER_POT", "FROSTED_ICE", "FURNACE", "GLASS", "GLASS_PANE",
				"GLOWSTONE", "GOLD_ORE", "GRANITE", "GRANITE_SLAB", "GRANITE_STAIRS", "GRANITE_WALL", "GRASS",
				"GRASS_BLOCK", "GRASS_PATH", "GRAVEL", "GRAY_BANNER", "GRAY_BED", "GRAY_CARPET", "GRAY_CONCRETE",
				"GRAY_CONCRETE_POWDER", "GRAY_GLAZED_TERRACOTTA", "GRAY_SHULKER_BOX", "GRAY_STAINED_GLASS",
				"GRAY_STAINED_GLASS_PANE", "GRAY_TERRACOTTA", "GRAY_WALL_BANNER", "GRAY_WOOL", "GREEN_BANNER",
				"GREEN_BED", "GREEN_CARPET", "GREEN_CONCRETE", "GREEN_CONCRETE_POWDER", "GREEN_GLAZED_TERRACOTTA",
				"GREEN_SHULKER_BOX", "GREEN_STAINED_GLASS", "GREEN_STAINED_GLASS_PANE", "GREEN_TERRACOTTA",
				"GREEN_WALL_BANNER", "GREEN_WOOL", "GRINDSTONE", "HAY_BALE", "HEAVY_WEIGHTED_PRESSURE_PLATE",
				"HONEY_BLOCK", "HONEYCOMB_BLOCK", "HOPPER", "HORN_CORAL", "HORN_CORAL_BLOCK", "HORN_CORAL_FAN",
				"HORN_CORAL_WALL_FAN", "ICE", "INFESTED_CHISELED_STONE_BRICKS", "INFESTED_COBBLESTONE",
				"INFESTED_CRACKED_STONE_BRICKS", "INFESTED_MOSSY_STONE_BRICKS", "INFESTED_STONE",
				"INFESTED_STONE_BRICKS", "IRON_BARS", "IRON_DOOR", "IRON_ORE", "IRON_TRAPDOOR", "JACK_O_LANTERN",
				"JIGSAW_BLOCK", "JUKEBOX", "JUNGLE_BUTTON", "JUNGLE_DOOR", "JUNGLE_FENCE", "JUNGLE_FENCE_GATE",
				"JUNGLE_LEAVES", "JUNGLE_LOG", "JUNGLE_PLANKS", "JUNGLE_PRESSURE_PLATE", "JUNGLE_SAPLING",
				"JUNGLE_SIGN", "JUNGLE_SLAB", "JUNGLE_STAIRS", "JUNGLE_TRAPDOOR", "JUNGLE_WALL_SIGN", "JUNGLE_WOOD",
				"KELP", "KELP_PLANT", "LADDER", "LANTERN", "LAPIS_BLOCK", "LAPIS_ORE", "LARGE_FERN", "LAVA", "LECTERN",
				"LEVER", "LIGHT_BLUE_BANNER", "LIGHT_BLUE_BED", "LIGHT_BLUE_CARPET", "LIGHT_BLUE_CONCRETE",
				"LIGHT_BLUE_CONCRETE_POWDER", "LIGHT_BLUE_GLAZED_TERRACOTTA", "LIGHT_BLUE_SHULKER_BOX",
				"LIGHT_BLUE_STAINED_GLASS", "LIGHT_BLUE_STAINED_GLASS_PANE", "LIGHT_BLUE_TERRACOTTA",
				"LIGHT_BLUE_WALL_BANNER", "LIGHT_BLUE_WOOL", "LIGHT_GRAY_BANNER", "LIGHT_GRAY_BED", "LIGHT_GRAY_CARPET",
				"LIGHT_GRAY_CONCRETE", "LIGHT_GRAY_CONCRETE_POWDER", "LIGHT_GRAY_GLAZED_TERRACOTTA",
				"LIGHT_GRAY_SHULKER_BOX", "LIGHT_GRAY_STAINED_GLASS", "LIGHT_GRAY_STAINED_GLASS_PANE",
				"LIGHT_GRAY_TERRACOTTA", "LIGHT_GRAY_WALL_BANNER", "LIGHT_GRAY_WOOL", "LIGHT_WEIGHTED_PRESSURE_PLATE",
				"LILAC", "LILY_PAD", "LILY_OF_THE_VALLEY", "LIME_BANNER", "LIME_BED", "LIME_CARPET", "LIME_CONCRETE",
				"LIME_CONCRETE_POWDER", "LIME_GLAZED_TERRACOTTA", "LIME_SHULKER_BOX", "LIME_STAINED_GLASS",
				"LIME_STAINED_GLASS_PANE", "LIME_TERRACOTTA", "LIME_WALL_BANNER", "LIME_WOOL", "LOOM", "MAGENTA_BANNER",
				"MAGENTA_BED", "MAGENTA_CARPET", "MAGENTA_CONCRETE", "MAGENTA_CONCRETE_POWDER",
				"MAGENTA_GLAZED_TERRACOTTA", "MAGENTA_SHULKER_BOX", "MAGENTA_STAINED_GLASS",
				"MAGENTA_STAINED_GLASS_PANE", "MAGENTA_TERRACOTTA", "MAGENTA_WALL_BANNER", "MAGENTA_WOOL",
				"MAGMA_BLOCK", "MELON", "MELON_STEM", "MOSSY_COBBLESTONE", "MOSSY_COBBLESTONE_SLAB",
				"MOSSY_COBBLESTONE_STAIRS", "MOSSY_COBBLESTONE_WALL", "MOSSY_STONE_BRICK_SLAB",
				"MOSSY_STONE_BRICK_STAIRS", "MOSSY_STONE_BRICK_WALL", "MOSSY_STONE_BRICKS", "MOVING_PISTON",
				"MUSHROOM_STEM", "MYCELIUM", "NETHER_BRICK_FENCE", "NETHER_BRICK_SLAB", "NETHER_BRICK_STAIRS",
				"NETHER_BRICK_WALL", "NETHER_BRICKS", "NETHER_PORTAL", "NETHER_QUARTZ_ORE", "NETHER_WART",
				"NETHER_WART_BLOCK", "NETHERRACK", "NOTE_BLOCK", "OAK_BUTTON", "OAK_DOOR", "OAK_FENCE",
				"OAK_FENCE_GATE", "OAK_LEAVES", "OAK_LOG", "OAK_PLANKS", "OAK_PRESSURE_PLATE", "OAK_SAPLING",
				"OAK_SIGN", "OAK_SLAB", "OAK_STAIRS", "OAK_TRAPDOOR", "OAK_WALL_SIGN", "OAK_WOOD", "OBSERVER",
				"OBSIDIAN", "ORANGE_BANNER", "ORANGE_BED", "ORANGE_CARPET", "ORANGE_CONCRETE", "ORANGE_CONCRETE_POWDER",
				"ORANGE_GLAZED_TERRACOTTA", "ORANGE_SHULKER_BOX", "ORANGE_STAINED_GLASS", "ORANGE_STAINED_GLASS_PANE",
				"ORANGE_TERRACOTTA", "ORANGE_TULIP", "ORANGE_WALL_BANNER", "ORANGE_WOOL", "OXEYE_DAISY", "PACKED_ICE",
				"PEONY", "PETRIFIED_OAK_SLAB", "PINK_BANNER", "PINK_BED", "PINK_CARPET", "PINK_CONCRETE",
				"PINK_CONCRETE_POWDER", "PINK_GLAZED_TERRACOTTA", "PINK_SHULKER_BOX", "PINK_STAINED_GLASS",
				"PINK_STAINED_GLASS_PANE", "PINK_TERRACOTTA", "PINK_TULIP", "PINK_WALL_BANNER", "PINK_WOOL", "PISTON",
				"PISTON_HEAD", "PLAYER_HEAD", "PLAYER_WALL_HEAD", "PODZOL", "POLISHED_ANDESITE",
				"POLISHED_ANDESITE_SLAB", "POLISHED_ANDESITE_STAIRS", "POLISHED_DIORITE", "POLISHED_DIORITE_SLAB",
				"POLISHED_DIORITE_STAIRS", "POLISHED_GRANITE", "POLISHED_GRANITE_SLAB", "POLISHED_GRANITE_STAIRS",
				"POPPY", "POTATOES", "POTTED_ACACIA_SAPLING", "POTTED_ALLIUM", "POTTED_AZURE_BLUET", "POTTED_BAMBOO",
				"POTTED_BIRCH_SAPLING", "POTTED_BLUE_ORCHID", "POTTED_BROWN_MUSHROOM", "POTTED_CACTUS",
				"POTTED_CORNFLOWER", "POTTED_DANDELION", "POTTED_DARK_OAK_SAPLING", "POTTED_DEAD_BUSH", "POTTED_FERN",
				"POTTED_JUNGLE_SAPLING", "POTTED_LILY_OF_THE_VALLEY", "POTTED_OAK_SAPLING", "POTTED_ORANGE_TULIP",
				"POTTED_OXEYE_DAISY", "POTTED_PINK_TULIP", "POTTED_POPPY", "POTTED_RED_MUSHROOM", "POTTED_RED_TULIP",
				"POTTED_SPRUCE_SAPLING", "POTTED_WHITE_TULIP", "POTTED_WITHER_ROSE", "POWERED_RAIL", "PRISMARINE",
				"PRISMARINE_BRICK_SLAB", "PRISMARINE_BRICK_STAIRS", "PRISMARINE_BRICKS", "PRISMARINE_SLAB",
				"PRISMARINE_STAIRS", "PRISMARINE_WALL", "PUMPKIN", "PUMPKIN_STEM", "PURPLE_BANNER", "PURPLE_BED",
				"PURPLE_CARPET", "PURPLE_CONCRETE", "PURPLE_CONCRETE_POWDER", "PURPLE_GLAZED_TERRACOTTA",
				"PURPLE_SHULKER_BOX", "PURPLE_STAINED_GLASS", "PURPLE_STAINED_GLASS_PANE", "PURPLE_TERRACOTTA",
				"PURPLE_WALL_BANNER", "PURPLE_WOOL", "PURPUR_BLOCK", "PURPUR_PILLAR", "PURPUR_SLAB", "PURPUR_STAIRS",
				"QUARTZ_PILLAR", "QUARTZ_SLAB", "QUARTZ_STAIRS", "RAIL", "RED_BANNER", "RED_BED", "RED_CARPET",
				"RED_CONCRETE", "RED_CONCRETE_POWDER", "RED_GLAZED_TERRACOTTA", "RED_MUSHROOM", "RED_MUSHROOM_BLOCK",
				"RED_NETHER_BRICK_SLAB", "RED_NETHER_BRICK_STAIRS", "RED_NETHER_BRICK_WALL", "RED_NETHER_BRICKS",
				"RED_SAND", "RED_SANDSTONE", "RED_SANDSTONE_SLAB", "RED_SANDSTONE_STAIRS", "RED_SANDSTONE_WALL",
				"RED_SHULKER_BOX", "RED_STAINED_GLASS", "RED_STAINED_GLASS_PANE", "RED_TERRACOTTA", "RED_TULIP",
				"RED_WALL_BANNER", "RED_WOOL", "REDSTONE_COMPARATOR", "REDSTONE_DUST", "REDSTONE_LAMP", "REDSTONE_ORE",
				"REDSTONE_REPEATER", "REDSTONE_TORCH", "REDSTONE_WALL_TORCH", "REPEATING_COMMAND_BLOCK", "ROSE_BUSH",
				"SAND", "SANDSTONE", "SANDSTONE_SLAB", "SANDSTONE_STAIRS", "SANDSTONE_WALL", "SCAFFOLDING",
				"SEA_LANTERN", "SEA_PICKLE", "SEAGRASS", "SHULKER_BOX", "SKELETON_SKULL", "SKELETON_WALL_SKULL",
				"SLIME_BLOCK", "SMITHING_TABLE", "SMOKER", "SMOOTH_QUARTZ", "SMOOTH_QUARTZ_SLAB",
				"SMOOTH_QUARTZ_STAIRS", "SMOOTH_RED_SANDSTONE", "SMOOTH_RED_SANDSTONE_SLAB",
				"SMOOTH_RED_SANDSTONE_STAIRS", "SMOOTH_SANDSTONE", "SMOOTH_SANDSTONE_SLAB", "SMOOTH_SANDSTONE_STAIRS",
				"SMOOTH_STONE", "SMOOTH_STONE_SLAB", "SNOW", "SNOW_BLOCK", "SOUL_SAND", "SPAWNER", "SPONGE",
				"SPRUCE_BUTTON", "SPRUCE_DOOR", "SPRUCE_FENCE", "SPRUCE_FENCE_GATE", "SPRUCE_LEAVES", "SPRUCE_LOG",
				"SPRUCE_PLANKS", "SPRUCE_PRESSURE_PLATE", "SPRUCE_SAPLING", "SPRUCE_SIGN", "SPRUCE_SLAB",
				"SPRUCE_STAIRS", "SPRUCE_TRAPDOOR", "SPRUCE_WALL_SIGN", "SPRUCE_WOOD", "STICKY_PISTON", "STONE",
				"STONE_BRICK_SLAB", "STONE_BRICK_STAIRS", "STONE_BRICK_WALL", "STONE_BRICKS", "STONE_BUTTON",
				"STONE_PRESSURE_PLATE", "STONE_SLAB", "STONE_STAIRS", "STONECUTTER", "STRIPPED_ACACIA_LOG",
				"STRIPPED_ACACIA_WOOD", "STRIPPED_BIRCH_LOG", "STRIPPED_BIRCH_WOOD", "STRIPPED_DARK_OAK_LOG",
				"STRIPPED_DARK_OAK_WOOD", "STRIPPED_JUNGLE_LOG", "STRIPPED_JUNGLE_WOOD", "STRIPPED_OAK_LOG",
				"STRIPPED_OAK_WOOD", "STRIPPED_SPRUCE_LOG", "STRIPPED_SPRUCE_WOOD", "STRUCTURE_BLOCK", "STRUCTURE_VOID",
				"SUGAR_CANE", "SUNFLOWER", "SWEET_BERRY_BUSH", "TNT", "TALL_GRASS", "TALL_SEAGRASS", "TERRACOTTA",
				"TORCH", "WALL_TORCH", "TRAPPED_CHEST", "TRIPWIRE", "TRIPWIRE_HOOK", "TUBE_CORAL", "TUBE_CORAL_BLOCK",
				"TUBE_CORAL_FAN", "TUBE_CORAL_WALL_FAN", "TURTLE_EGG", "VINES", "VOID_AIR", "WATER", "WET_SPONGE",
				"WHEAT", "WHITE_BANNER", "WHITE_BED", "WHITE_CARPET", "WHITE_CONCRETE", "WHITE_CONCRETE_POWDER",
				"WHITE_GLAZED_TERRACOTTA", "WHITE_SHULKER_BOX", "WHITE_STAINED_GLASS", "WHITE_STAINED_GLASS_PANE",
				"WHITE_TERRACOTTA", "WHITE_TULIP", "WHITE_WALL_BANNER", "WHITE_WOOL", "WITHER_ROSE",
				"WITHER_SKELETON_SKULL", "WITHER_SKELETON_WALL_SKULL", "YELLOW_BANNER", "YELLOW_BED", "YELLOW_CARPET",
				"YELLOW_CONCRETE", "YELLOW_CONCRETE_POWDER", "YELLOW_GLAZED_TERRACOTTA", "YELLOW_SHULKER_BOX",
				"YELLOW_STAINED_GLASS", "YELLOW_STAINED_GLASS_PANE", "YELLOW_TERRACOTTA", "YELLOW_WALL_BANNER",
				"YELLOW_WOOL", "ZOMBIE_HEAD", "ZOMBIE_WALL_HEAD" };

		String[] extraMaterials = { "WALL_TORCH_NORTH", "WALL_TORCH_EAST", "WALL_TORCH_SOUTH", "WALL_TORCH_WEST", };

		String[] sourcecraftMade = { "_STAIRS_SMALL_EAST_SOUTH", "_STAIRS_SMALL_EAST_NORTH", "_STAIRS_SMALL_WEST_SOUTH",
				"_STAIRS_SMALL_WEST_NORTH", "_STAIRS_BIG_EAST_SOUTH", "_STAIRS_BIG_EAST_NORTH",
				"_STAIRS_BIG_WEST_SOUTH", "_STAIRS_BIG_WEST_NORTH", "_STAIRS_EAST", "_STAIRS_WEST", "_STAIRS_NORTH",
				"_STAIRS_SOUTH", "_STAIRS_SMALL_EAST_SOUTH_RERUN", "_STAIRS_SMALL_EAST_NORTH_RERUN",
				"_STAIRS_SMALL_WEST_SOUTH_RERUN", "_STAIRS_SMALL_WEST_NORTH_RERUN", "_STAIRS_BIG_EAST_SOUTH_RERUN",
				"_STAIRS_BIG_EAST_NORTH_RERUN", "_STAIRS_BIG_WEST_SOUTH_RERUN", "_STAIRS_BIG_WEST_NORTH_RERUN",
				"_PLAYER_CLIP", "_UNKOWN" };

		List<String> list = new ArrayList<>();
		for (String in : minecraftMaerial) {
			list.add(in);
		}
		Collections.sort(list);
		System.out.println("public static final int " + "_UNSET" + " = " + 0 + ";");
		int index = 1;
		for (String name : list) {
			if (name.endsWith("_STAIRS")) {
				System.out.println("public static final int " + name + " = " + index++ + ";");
				for (String facing : new String[] { "EAST", "SOUTH", "NORTH", "WEST" }) {
					for (String half : new String[] { "TOP", "BOTTOM" }) {
						for (String shape : new String[] { "INNER_LEFT", "INNER_RIGHT", "OUTER_LEFT", "OUTER_RIGHT",
								"STRAIGHT" }) {
							System.out.println("public static final int " + name + DETAIL + half + DETAIL + facing
									+ DETAIL + shape + " = " + index++ + ";");
						}
					}
				}
			} else if (name.endsWith("_SLAB")) {
				System.out.println("public static final int " + name + DETAIL + "BOTTOM = " + index++ + ";");
				System.out.println("public static final int " + name + DETAIL + "DOUBLE = " + index++ + ";");
				System.out.println("public static final int " + name + DETAIL + "TOP = " + index++ + ";");
			} else if (name.endsWith("CHEST") || name.endsWith("WALL_TORCH")) {
				for (String facing : new String[] { "EAST", "SOUTH", "NORTH", "WEST" }) {
					System.out.println("public static final int " + name + DETAIL + facing + " = " + index++ + ";");
				}
			} else {

				System.out.println("public static final int " + name + " = " + index++ + ";");
			}
		}
		for (String in : extraMaterials) {
			System.out.println("public static final int " + in + " = " + index + ";");
			index++;
		}
		for (String in : sourcecraftMade) {
			System.out.println("public static final int " + in + " = " + index + ";");
			index++;
		}
	}
}
